#!/usr/bin/env bash
# =============================================================================
# pgmigrate installer
#
# Usage:
#   ./install.sh                  Install to /usr/local (default)
#   ./install.sh --prefix ~/.local  Install to a custom prefix
#   ./install.sh --uninstall      Remove a previously installed pgmigrate
#
# What it does:
#   1. Copies the library to <prefix>/lib/pgmigrate/
#   2. Installs a launcher script at <prefix>/bin/pgmigrate
# =============================================================================

set -euo pipefail

# ---- Defaults ---------------------------------------------------------------

PREFIX="/usr/local"
UNINSTALL=false
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- Colors (inline — installer runs before lib/ is available) --------------

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${NC}  $1"; }
log_success() { echo -e "${GREEN}[OK]${NC}    $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }

# ---- Argument parsing -------------------------------------------------------

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix)
      PREFIX="${2:?--prefix requires a value}"
      shift 2
      ;;
    --uninstall)
      UNINSTALL=true
      shift
      ;;
    -h|--help)
      echo "Usage: ./install.sh [--prefix <dir>] [--uninstall]"
      echo ""
      echo "  --prefix <dir>   Installation prefix (default: /usr/local)"
      echo "  --uninstall      Remove pgmigrate from the given prefix"
      exit 0
      ;;
    *)
      log_error "Unknown option: $1"
      echo "Run './install.sh --help' for usage."
      exit 1
      ;;
  esac
done

LIB_DIR="${PREFIX}/lib/pgmigrate"
BIN_FILE="${PREFIX}/bin/pgmigrate"

# ---- Uninstall --------------------------------------------------------------

if [[ "$UNINSTALL" == true ]]; then
  log_info "Uninstalling pgmigrate from ${PREFIX}..."

  if [[ -d "$LIB_DIR" ]]; then
    rm -rf "$LIB_DIR"
    log_success "Removed ${LIB_DIR}"
  else
    log_warn "${LIB_DIR} not found — skipping."
  fi

  if [[ -f "$BIN_FILE" ]]; then
    rm -f "$BIN_FILE"
    log_success "Removed ${BIN_FILE}"
  else
    log_warn "${BIN_FILE} not found — skipping."
  fi

  log_success "pgmigrate uninstalled."
  exit 0
fi

# ---- Pre-flight checks ------------------------------------------------------

log_info "Checking dependencies..."

missing=()
for cmd in psql pg_dump; do
  if ! command -v "$cmd" &>/dev/null; then
    missing+=("$cmd")
  fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
  log_warn "The following dependencies were not found in PATH: ${missing[*]}"
  log_warn "pgmigrate will not work until they are installed."
  echo ""
fi

if [[ ! -d "${PREFIX}/bin" ]]; then
  log_error "Target bin directory does not exist: ${PREFIX}/bin"
  log_info  "Create it first or choose a different --prefix."
  exit 1
fi

# ---- Install ----------------------------------------------------------------

log_info "Installing pgmigrate to ${PREFIX}..."

# Copy library files
mkdir -p "${LIB_DIR}/lib"
mkdir -p "${LIB_DIR}/commands"

cp "${REPO_DIR}/migrate.sh"           "${LIB_DIR}/migrate.sh"
cp "${REPO_DIR}/lib/constants.sh"     "${LIB_DIR}/lib/constants.sh"
cp "${REPO_DIR}/lib/helpers.sh"       "${LIB_DIR}/lib/helpers.sh"
cp "${REPO_DIR}/lib/db.sh"            "${LIB_DIR}/lib/db.sh"
cp "${REPO_DIR}/lib/snapshot.sh"      "${LIB_DIR}/lib/snapshot.sh"
cp "${REPO_DIR}/commands/help.sh"     "${LIB_DIR}/commands/help.sh"
cp "${REPO_DIR}/commands/up.sh"       "${LIB_DIR}/commands/up.sh"
cp "${REPO_DIR}/commands/down.sh"     "${LIB_DIR}/commands/down.sh"
cp "${REPO_DIR}/commands/status.sh"   "${LIB_DIR}/commands/status.sh"
cp "${REPO_DIR}/commands/create.sh"   "${LIB_DIR}/commands/create.sh"
cp "${REPO_DIR}/commands/snapshot.sh" "${LIB_DIR}/commands/snapshot.sh"

chmod +x "${LIB_DIR}/migrate.sh"

log_success "Library installed to ${LIB_DIR}"

# Write the launcher — delegates to the installed migrate.sh, handles uninstall
cat > "${BIN_FILE}" <<EOF
#!/usr/bin/env bash
# pgmigrate launcher — auto-generated by install.sh
if [[ "\${1:-}" == "uninstall" ]]; then
  echo "Uninstalling pgmigrate..."
  rm -rf "${LIB_DIR}" && echo "[OK]  Removed ${LIB_DIR}"
  rm -f  "${BIN_FILE}" && echo "[OK]  Removed ${BIN_FILE}"
  echo "[OK]  pgmigrate uninstalled."
  exit 0
fi
exec "${LIB_DIR}/migrate.sh" "\$@"
EOF

chmod +x "${BIN_FILE}"

log_success "Launcher installed at ${BIN_FILE}"

# ---- Post-install guidance --------------------------------------------------

echo ""
log_success "pgmigrate installed successfully."
echo ""

# Check whether the bin dir is in PATH
if [[ ":${PATH}:" != *":${PREFIX}/bin:"* ]]; then
  log_warn "${PREFIX}/bin is not in your PATH."
  echo ""
  echo "  Add this line to your shell profile (~/.zshrc, ~/.bashrc, etc.):"
  echo ""
  echo "    export PATH=\"${PREFIX}/bin:\$PATH\""
  echo ""
  echo "  Then reload your shell:"
  echo ""
  echo "    source ~/.zshrc   # or ~/.bashrc"
  echo ""
fi

echo "  To get started in a project:"
echo ""
echo "    cd your-project/"
echo "    cp ${LIB_DIR}/../.env.example .env   # or create your own .env"
echo "    pgmigrate help"
echo ""
echo "  To uninstall:"
echo ""
echo "    pgmigrate uninstall"
echo ""
